version: '3.9'

services:
  farmcalendar_db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${FARM_CALENDAR_POSTGRES_DB}
      POSTGRES_USER: ${FARM_CALENDAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FARM_CALENDAR_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $FARM_CALENDAR_POSTGRES_USER -d $FARM_CALENDAR_POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  farmcalendar:
    image: ghcr.io/openagri-eu/farmcalendar:latest
    command: /var/www/entrypoint.sh
    ports:
      - "${FARM_CALENDAR_APP_PORT}:${FARM_CALENDAR_APP_PORT}"
    environment:
      APP_HOST: ${FARM_CALENDAR_APP_HOST}
      APP_PORT: ${FARM_CALENDAR_APP_PORT}
      POSTGRES_HOST: farmcalendar_db
      POSTGRES_DB: ${FARM_CALENDAR_POSTGRES_DB}
      POSTGRES_USER: ${FARM_CALENDAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FARM_CALENDAR_POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${FARM_CALENDAR_DJANGO_SECRET_KEY}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      GATEKEEPER_LOGIN_URL: ${GATEKEEPER_LOGIN_URL}
      GATEKEEPER_API_LOGIN_URL: ${GATEKEEPER_API_LOGIN_URL}
      GATEKEEPER_ENDPOINT_REG_URL: ${GATEKEEPER_ENDPOINT_REG_URL}
      INTERNAL_SERVICE_NAME: farmcalendar
      FARMCALENDAR_GATEKEEPER_USER: ${GATEKEEPER_SUPERUSER_USERNAME}
      FARMCALENDAR_GATEKEEPER_PASSWORD: ${GATEKEEPER_SUPERUSER_PASSWORD}
      AUTO_CREATE_AUTH_USER: True
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      EXTRA_ALLOWED_HOSTS: ${FARM_CALENDAR_EXTRA_ALLOWED_HOSTS}
      VIRTUAL_HOST: ${FARM_CALENDAR_VIRTUAL_HOST}
      VIRTUAL_PORT: ${FARM_CALENDAR_APP_PORT}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      NO_PROXY: ${DEFAULT_NO_PROXY},farmcalendar_db
    depends_on:
      farmcalendar_db:
        condition: service_healthy
      gatekeeper:
        condition: service_started