services:
  pest_and_desease_management_db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_DB}
      POSTGRES_USER: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_PASSWORD}
      PGPORT: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_USER} -d ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3
  pest_and_desease_management:
    depends_on:
      pest_and_desease_management_db:
        condition: service_healthy
    image: ghcr.io/openagri-eu/pest-and-disease-management:latest
    command: /code/entrypoint.sh
    ports:
      - "${PEST_AND_DESEASE_MANAGEMENT_APP_PORT}:${PEST_AND_DESEASE_MANAGEMENT_APP_PORT}"
    environment:
      POSTGRES_HOST: pest_and_desease_management_db
      POSTGRES_USER: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_DB}
      POSTGRES_PORT: ${PEST_AND_DESEASE_MANAGEMENT_POSTGRES_PORT}
      APP_PORT: ${PEST_AND_DESEASE_MANAGEMENT_APP_PORT}
      GATEKEEPER_LOGIN_API_URL: ${GATEKEEPER_LOGIN_API_URL}
      ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      JWT_KEY: ${JWT_SIGNING_KEY}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      VIRTUAL_HOST: ${PEST_AND_DESEASE_MANAGEMENT_VIRTUAL_HOST}
      VIRTUAL_PORT: ${PEST_AND_DESEASE_MANAGEMENT_APP_PORT}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      NO_PROXY: ${DEFAULT_NO_PROXY},pest_and_desease_management_db